parameters:
#    acme_orchestra.example.class: Acme\OrchestraBundle\Example

services:
#    acme_orchestra.example:
#        class: %acme_orchestra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
