acme_library_livre_create:
    pattern:  /library/livre/create
    defaults: { _controller: AcmeLibraryBundle:Default:create }
    
acme_library_livre_show:
    pattern:  /library/livre/show/{id}
    defaults: { _controller: AcmeLibraryBundle:Default:show }
    
acme_library_book_update:
    pattern:  /library/livre/update/{id}
    defaults: { _controller: AcmeLibraryBundle:Default:update }
    
acme_library_book_delete:
    pattern:  /library/livre/suppr/{id}
    defaults: { _controller: AcmeLibraryBundle:Default:suppr} 